//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesFormatoPedido.Service1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service1.IMetodos")]
    public interface IMetodos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetodos/GetData", ReplyAction="http://tempuri.org/IMetodos/GetDataResponse")]
        string GetData(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetodos/listaArt", ReplyAction="http://tempuri.org/IMetodos/listaArtResponse")]
        ServiceBB.DataContract.DC_Articulos[] listaArt();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetodos/Ncolor", ReplyAction="http://tempuri.org/IMetodos/NcolorResponse")]
        string Ncolor(string color);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetodos/datosCte", ReplyAction="http://tempuri.org/IMetodos/datosCteResponse")]
        ServiceBB.DataContract.DC_datosCte datosCte(string clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMetodos/DetalleVenta", ReplyAction="http://tempuri.org/IMetodos/DetalleVentaResponse")]
        void DetalleVenta(ServiceBB.DataContract.DC_venta venta);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMetodosChannel : DesFormatoPedido.Service1.IMetodos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MetodosClient : System.ServiceModel.ClientBase<DesFormatoPedido.Service1.IMetodos>, DesFormatoPedido.Service1.IMetodos {
        
        public MetodosClient() {
        }
        
        public MetodosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MetodosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MetodosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MetodosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(string value) {
            return base.Channel.GetData(value);
        }
        
        public ServiceBB.DataContract.DC_Articulos[] listaArt() {
            return base.Channel.listaArt();
        }
        
        public string Ncolor(string color) {
            return base.Channel.Ncolor(color);
        }
        
        public ServiceBB.DataContract.DC_datosCte datosCte(string clave) {
            return base.Channel.datosCte(clave);
        }
        
        public void DetalleVenta(ServiceBB.DataContract.DC_venta venta) {
            base.Channel.DetalleVenta(venta);
        }
    }
}
